// myApp/src/components/PRDView.tsx
import React, { useState } from "react";
import {
  Target,
  Users,
  ListChecks,
  Flag,
  Zap,
  Sparkles,
  ShieldCheck,
  LayoutGrid,
  Activity,
  Download,
} from "lucide-react";

// IMPORTANT: Requires jspdf and jspdf-autotable
// Run: npm install jspdf jspdf-autotable
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export default function PRDView({ allData }: { allData: any[] }) {
  const [activeTab, setActiveTab] = useState("all");

  // 1. Data Aggregation Logic
  const aggregated = {
    functional: [
      ...new Set(
        allData.flatMap(
          (d) => d.analysis_details?.functional_requirements || [],
        ),
      ),
    ],
    nonFunctional: [
      ...new Set(
        allData.flatMap(
          (d) => d.analysis_details?.non_functional_requirements || [],
        ),
      ),
    ],
    stakeholders: [
      ...new Set(
        allData.flatMap((d) => d.analysis_details?.stakeholders || []),
      ),
    ],
    timelines: [
      ...new Set(allData.flatMap((d) => d.analysis_details?.timelines || [])),
    ],
    decisions: [
      ...new Set(allData.flatMap((d) => d.analysis_details?.decisions || [])),
    ],
  };

  const rawID =
    allData[0]?.metadata?.project_id || allData[0]?.project_id || "GLOBAL";
  const projectID = rawID.length > 15 ? `${rawID.substring(0, 12)}...` : rawID;

  // 2. Structured PDF Generation Logic
  const downloadPDF = () => {
    const doc = new jsPDF();
    const primaryColor = [71, 41, 224]; // ReqMind Indigo
    const textColor = [40, 40, 40];

    // Variables for document naming and IDs
    const finalRawID =
      allData[0]?.metadata?.project_id ||
      allData[0]?.project_id ||
      "69C649C0DF4A...";
    const finalProjectID =
      finalRawID.length > 15 ? `${finalRawID.substring(0, 12)}...` : finalRawID;

    // --- 1. COVER PAGE ---
    doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.rect(0, 0, 210, 297, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(40);
    doc.setFont("helvetica", "bold");
    doc.text("BRD", 20, 80);

    doc.setFontSize(22);
    doc.text("Business Requirements Document", 20, 95);

    doc.setLineWidth(1);
    doc.setDrawColor(255, 255, 255);
    doc.line(20, 105, 80, 105);

    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(`PROJECT ID: ${finalRawID}`, 20, 125);
    doc.text(`GENERATED BY: ReqMind AI Intelligence`, 20, 133);
    doc.text(`DATE: ${new Date().toLocaleDateString()}`, 20, 141);

    // --- 2. INDEX PAGE ---
    doc.addPage();
    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text("INDEX", 20, 40);

    doc.setDrawColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.setLineWidth(0.5);
    doc.line(20, 45, 40, 45);

    doc.setTextColor(textColor[0], textColor[1], textColor[2]);
    doc.setFontSize(12);
    const indexItems = [
      "1. Key Decisions",
      "2. Functional Requirements",
      "3. Non-Functional Requirements",
      "4. Release Timeline",
      "5. Stakeholder Registry",
    ];

    indexItems.forEach((item, index) => {
      const y = 65 + index * 12;
      doc.setFont("helvetica", "bold");
      doc.text(item, 20, y);
      doc.setFont("helvetica", "normal");
      doc.text(
        "........................................................................................",
        80,
        y,
      );
      doc.text(`0${index + 3}`, 185, y); // Data starts at Page 3
    });

    // --- 3. DATA CONTENT ---
    // Ensuring the sections follow your exact requested sequence
    const sections = [
      {
        title: "1. Key Decisions",
        data: aggregated.decisions,
        label: "Decision Log",
      },
      {
        title: "2. Functional Requirements",
        data: aggregated.functional,
        label: "Requirement Description",
      },
      {
        title: "3. Non-Functional Requirements",
        data: aggregated.nonFunctional,
        label: "Quality Standard",
      },
      {
        title: "4. Release Timeline",
        data: aggregated.timelines,
        label: "Milestone / Date",
      },
      {
        title: "5. Stakeholder Registry",
        data: aggregated.stakeholders,
        label: "Stakeholder / Role",
      },
    ];

    sections.forEach((section) => {
      if (section.data && section.data.length > 0) {
        doc.addPage(); // Every major section starts on a fresh page
        let yPos = 30;

        doc.setFontSize(16);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
        doc.text(section.title.toUpperCase(), 14, yPos);

        autoTable(doc, {
          startY: yPos + 8,
          head: [[section.label.toUpperCase()]],
          body: section.data.map((item: any) => [
            typeof item === "string"
              ? item.replace(/[#*]/g, "").trim()
              : JSON.stringify(item),
          ]),
          theme: "grid",
          styles: { fontSize: 10, cellPadding: 5, font: "helvetica" },
          headStyles: {
            fillColor: [245, 245, 250],
            textColor: primaryColor,
            fontStyle: "bold",
          },
          margin: { left: 14, right: 14 },
        });
      }
    });

    // --- 4. FOOTER ---
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 2; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(
        `ReqMind AI • CONFIDENTIAL • Page ${i} of ${pageCount}`,
        105,
        285,
        { align: "center" },
      );
    }

    doc.save(`BRD_${finalProjectID}.pdf`);
  };
  const tabs = [
    { id: "all", label: "ALL", icon: LayoutGrid, color: "text-indigo-400" },
    { id: "decisions", label: "DECISIONS", icon: Zap, color: "text-amber-400" },
    {
      id: "functional",
      label: "FUNCTIONAL",
      icon: Target,
      color: "text-blue-400",
    },
    {
      id: "nonFunctional",
      label: "NON-FUNCTIONAL",
      icon: ShieldCheck,
      color: "text-emerald-400",
    },
    { id: "timelines", label: "TIMELINES", icon: Flag, color: "text-sky-400" },
    {
      id: "stakeholders",
      label: "STAKEHOLDERS",
      icon: Users,
      color: "text-purple-400",
    },
  ];

  const SectionHeader = ({ icon: Icon, title, color }: any) => (
    <div className="flex items-center gap-3 mb-4 group pt-2">
      <div className={`p-2 rounded-lg bg-slate-800/50 border border-slate-700`}>
        <Icon className={`w-5 h-5 ${color}`} />
      </div>
      <h3 className="text-sm font-black text-slate-400 uppercase tracking-[0.2em]">
        {title}
      </h3>
      <div className="h-px flex-1 bg-gradient-to-r from-slate-800 to-transparent ml-2" />
    </div>
  );

  const renderDecisions = (showTitle = true) => (
    <div className="space-y-4 animate-in fade-in duration-500">
      {showTitle && (
        <SectionHeader
          icon={Zap}
          title="Key Decisions"
          color="text-amber-500"
        />
      )}
      <div className="grid grid-cols-1 gap-4">
        {aggregated.decisions.length > 0 ? (
          aggregated.decisions.map((item, i) => (
            <div
              key={i}
              className="p-5 bg-[#1c1a2e] border border-slate-800 rounded-2xl flex gap-4 border-l-amber-500/50 border-l-2"
            >
              <div className="flex flex-col">
                <span className="text-xs text-amber-500/70 font-black font-mono tracking-widest uppercase mb-1">
                  Decision #0{i + 1}
                </span>
                <p className="text-slate-300 text-base leading-relaxed font-medium">
                  {item}
                </p>
              </div>
            </div>
          ))
        ) : (
          <p className="text-slate-500 italic text-sm ml-4 py-1">
            No decisions identified yet.
          </p>
        )}
      </div>
    </div>
  );

  const renderFunctional = (showTitle = true) => (
    <div className="space-y-4 animate-in fade-in duration-500">
      {showTitle && (
        <SectionHeader
          icon={Target}
          title="Functional Requirements"
          color="text-blue-400"
        />
      )}
      <div className="space-y-3">
        {aggregated.functional.length > 0 ? (
          aggregated.functional.map((req, i) => (
            <div
              key={i}
              className="p-5 bg-[#1c1a2e]/50 border border-slate-800 rounded-xl flex items-start gap-4 border-l-blue-500/50 border-l-2"
            >
              <Activity className="w-5 h-5 text-blue-500 mt-1 shrink-0" />
              <p className="text-slate-300 text-base italic leading-relaxed">
                "As a{" "}
                <span className="text-white font-bold">
                  {aggregated.stakeholders[0] || "User"}
                </span>
                , I want to{" "}
                <span className="text-white">
                  {req.toLowerCase().replace(/\.$/, "")}
                </span>
                ."
              </p>
            </div>
          ))
        ) : (
          <p className="text-slate-500 italic text-sm ml-4 py-1">
            No functional requirements identified yet.
          </p>
        )}
      </div>
    </div>
  );

  const renderNonFunctional = (showTitle = true) => (
    <div className="space-y-4 animate-in fade-in duration-500">
      {showTitle && (
        <SectionHeader
          icon={ShieldCheck}
          title="Quality Standards"
          color="text-emerald-400"
        />
      )}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {aggregated.nonFunctional.length > 0 ? (
          aggregated.nonFunctional.map((req, i) => (
            <div
              key={i}
              className="p-5 bg-[#1c1a2e] border border-slate-800 rounded-xl border-t-2 border-t-emerald-500/50"
            >
              <p className="text-slate-400 text-base leading-snug">{req}</p>
            </div>
          ))
        ) : (
          <p className="text-slate-500 italic text-sm ml-4 py-1">
            No quality standards identified yet.
          </p>
        )}
      </div>
    </div>
  );

  const renderTimelines = (showTitle = true) => (
    <div className="animate-in fade-in duration-500 space-y-4">
      {showTitle && (
        <SectionHeader
          icon={Flag}
          title="Release Timeline"
          color="text-sky-400"
        />
      )}
      <div className="pl-2">
        <ul className="space-y-5">
          {aggregated.timelines.length > 0 ? (
            aggregated.timelines.map((time, i) => (
              <li key={i} className="flex items-start gap-5 group">
                <div className="mt-2 shrink-0 w-2 h-2 rounded-full bg-sky-500 shadow-[0_0_8px_rgba(14,165,233,0.4)]" />
                <p className="text-slate-300 text-base leading-relaxed tracking-tight">
                  {time.replace(/[#*]/g, "").trim()}
                </p>
              </li>
            ))
          ) : (
            <p className="text-slate-500 italic text-sm ml-6">
              No timelines identified yet.
            </p>
          )}
        </ul>
      </div>
    </div>
  );

  const renderStakeholders = (showTitle = true) => (
    <div className="space-y-4 animate-in fade-in duration-700">
      {showTitle && (
        <SectionHeader
          icon={Users}
          title="Stakeholders"
          color="text-purple-400"
        />
      )}
      <div className="flex flex-wrap gap-3">
        {aggregated.stakeholders.length > 0 ? (
          aggregated.stakeholders.map((person, i) => (
            <div
              key={i}
              className="px-4 py-2 bg-slate-800/30 border border-slate-700/50 rounded-lg flex items-center gap-3"
            >
              <div className="w-2 h-2 rounded-full bg-purple-500" />
              <span className="text-sm text-slate-300 font-bold uppercase tracking-wider">
                {person}
              </span>
            </div>
          ))
        ) : (
          <p className="text-slate-500 italic text-sm ml-4 py-1">
            No stakeholders identified yet.
          </p>
        )}
      </div>
    </div>
  );

  return (
    <div className="p-8 max-w-6xl mx-auto space-y-6 animate-in fade-in duration-700">
      {/* HEADER SECTION */}
      <header className="flex flex-col md:flex-row justify-between items-center gap-8 py-6 px-2">
        <div className="flex items-center gap-5">
          <div className="bg-[#4729e0] p-3 rounded-2xl shadow-[0_0_20px_rgba(71,41,224,0.3)]">
            <Sparkles className="w-7 h-7 text-white" />
          </div>
          <div className="text-left">
            <h1 className="text-3xl font-black text-white tracking-tighter uppercase leading-none">
              Master <span className="text-[#4729e0]">BRD</span> Report
            </h1>
            <p className="text-slate-500 font-mono text-xs mt-2 tracking-[0.2em] uppercase leading-none">
              Structured Intelligence Hub
            </p>
          </div>
        </div>

        <button
          onClick={downloadPDF}
          className="flex items-center gap-3 px-6 py-3 bg-[#4729e0] hover:bg-[#3a21b8] text-white rounded-xl text-sm font-black tracking-widest transition-all active:scale-95 group shadow-lg shadow-[#4729e0]/20"
        >
          <Download className="w-5 h-5 group-hover:translate-y-0.5 transition-transform" />
          DOWNLOAD BRD
        </button>
      </header>

      {/* STICKY NAVIGATION */}
      <div className="flex flex-wrap gap-2 justify-center p-2 bg-[#1c1a2e]/90 backdrop-blur-3xl border border-slate-800 rounded-2xl sticky top-2 z-30 shadow-xl mb-2">
        {tabs.map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`flex items-center gap-2 px-5 py-2.5 rounded-xl text-xs font-black tracking-widest transition-all duration-300 ${
              activeTab === tab.id
                ? "bg-[#4729e0] text-white shadow-md scale-105"
                : "text-slate-400 hover:bg-slate-800 hover:text-slate-300"
            }`}
          >
            <tab.icon
              className={`w-4 h-4 ${activeTab === tab.id ? "text-white" : tab.color}`}
            />
            {tab.label}
          </button>
        ))}
      </div>

      {/* MAIN CONTENT AREA */}
      <main className="space-y-10 mt-6 min-h-[50vh]">
        {activeTab === "all" ? (
          <>
            {renderDecisions()}
            {renderFunctional()}
            {renderNonFunctional()}
            {renderTimelines()}
            {renderStakeholders()}
          </>
        ) : (
          <div className="pt-4">
            {activeTab === "decisions" && renderDecisions(false)}
            {activeTab === "functional" && renderFunctional(false)}
            {activeTab === "nonFunctional" && renderNonFunctional(false)}
            {activeTab === "timelines" && renderTimelines(false)}
            {activeTab === "stakeholders" && renderStakeholders(false)}
          </div>
        )}
      </main>
    </div>
  );
}
